services:
  db-c:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: test_db_c
      MYSQL_TCP_PORT: 3306
    ports:
      - "9903:3306"
  web:
    build: 
      context: ../
      dockerfile: Dockerfile
    environment:
      HOST_NAME: sql-c-web-1
      HOST_THEME_COLOR: dodgerblue
      HOST_DB_ADRESS: db-c
      HOST_DB_PORT: 3306
      HOST_DB_USER: root
      HOST_DB_PASSWORD: rootpass
      HOST_DB_NAME: test_db_c
      HOST_ADRESS: localhost
      HOST_PORT: 8103
      HOST_PMA_PORT: 8083
    depends_on:
      - db-c
    volumes:
      - ../src/:/var/www/html/
    restart: always
    ports:
      - "8103:80"
  phpmyadmin:
    image: phpmyadmin:5.2-apache
    links:
      - db-c
    environment:
      PMA_HOST: db-c
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - "8083:80"