services:
  db-a:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: test_db_a
      MYSQL_TCP_PORT: 3306
    ports:
      - "9901:3306"
  web:
    build: 
      context: ../
      dockerfile: Dockerfile
    environment:
      HOST_NAME: sql-a-web-1
      HOST_THEME_COLOR: orange
      HOST_DB_ADRESS: db-a
      HOST_DB_PORT: 3306
      HOST_DB_USER: root
      HOST_DB_PASSWORD: rootpass
      HOST_DB_NAME: test_db_a
      HOST_ADRESS: localhost
      HOST_PORT: 8101
      HOST_PMA_PORT: 8081
    depends_on:
      - db-a
    volumes:
      - ../src/:/var/www/html/
    restart: always
    ports:
      - "8101:80"
  phpmyadmin:
    image: phpmyadmin:5.2-apache
    links:
      - db-a
    environment:
      PMA_HOST: db-a
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - "8081:80"