services:
  db-a:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: test_db_a
      MYSQL_TCP_PORT: 3306
    ports:
      - "9901:3306"
  web:
    image: php:7.4-apache
    environment:
      TENANT_ID: ten-a
    depends_on:
      - db-a
    volumes:
      - ../src/:/var/www/html/
    ports:
      - "8101:80"
  phpmyadmin:
    image: phpmyadmin:5.2-apache
    links:
      - db-a
    environment:
      PMA_HOST: db-a
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - "8081:80"