services:
  db-b:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: test_db_b
      MYSQL_TCP_PORT: 3306
    ports:
      - "9902:3306"
  web:
    build: 
      context: ../
      dockerfile: Dockerfile
    environment:
      HOST_NAME: sql-b-web-1
      HOST_THEME_COLOR: mediumseagreen
      HOST_DB_ADRESS: db-b
      HOST_DB_PORT: 3306
      HOST_DB_USER: root
      HOST_DB_PASSWORD: rootpass
      HOST_DB_NAME: test_db_b
      HOST_ADRESS: localhost
      HOST_PORT: 8102
      HOST_PMA_PORT: 8082
    depends_on:
      - db-b
    volumes:
      - ../src/:/var/www/html/
    restart: always
    ports:
      - "8102:80"
  phpmyadmin:
    image: phpmyadmin:5.2-apache
    links:
      - db-b
    environment:
      PMA_HOST: db-b
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - "8082:80"